#!/usr/bin/env bash
set -euo pipefail
ENGINE_BIN="${CONTAINER_ENGINE_BIN:-docker}"

engine() {
  "$ENGINE_BIN" "$@"
}

host_path() {
  local path="$1"
  if [[ "$ENGINE_BIN" == *.exe ]] && command -v wslpath >/dev/null 2>&1; then
    wslpath -w "$path"
  else
    printf '%s\n' "$path"
  fi
}

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_TAG="${IMAGE_TAG:-zerodast-scanner:2.17.0}"
REPORTS_DIR="${REPORTS_DIR:-$ROOT_DIR/reports/benchmark}"
HOST_ROOT_DIR="$(host_path "$ROOT_DIR")"
mkdir -p "$REPORTS_DIR"

echo "=== Building surgical image ==="
engine build -t "$IMAGE_TAG" -f "$HOST_ROOT_DIR\\docker\\Dockerfile.zerodast-scanner" "$HOST_ROOT_DIR\\docker"

echo "=== Image size ==="
engine images "$IMAGE_TAG" --format '{{.Repository}}:{{.Tag}} {{.Size}}'

STOCK_TAG="${STOCK_TAG:-zaproxy/zap-stable:2.17.0}"
{
  echo "# ZAP image size comparison"
  echo ""
  echo "Generated by scripts/build-surgical-image.sh (do not edit by hand unless updating numbers)."
  echo ""
  echo "## Stock (reference)"
  engine images "$STOCK_TAG" --format '- {{.Repository}}:{{.Tag}} **{{.Size}}**' 2>/dev/null || echo "- (pull $STOCK_TAG locally to record size)"
  echo ""
  echo "## Surgical"
  engine images "$IMAGE_TAG" --format '- {{.Repository}}:{{.Tag}} **{{.Size}}**'
} > "$REPORTS_DIR/image-sizes.md"

echo "=== Addon inventory ==="
engine run --rm "$IMAGE_TAG" sh -c 'ls -1 /zap/plugin/*.zap 2>/dev/null; ls -1 /home/zap/.ZAP/plugin/*.zap 2>/dev/null' | sort

echo "=== Addon count ==="
engine run --rm "$IMAGE_TAG" sh -c '
  count=0
  for d in /zap/plugin /home/zap/.ZAP/plugin; do
    if [ -d "$d" ]; then count=$((count + $(ls -1 "$d"/*.zap 2>/dev/null | wc -l))); fi
  done
  echo "$count addons installed"
'

echo "=== Startup test ==="
engine run --rm "$IMAGE_TAG" zap.sh -cmd -version

echo "Wrote $REPORTS_DIR/image-sizes.md"
